# Generated by Django 6.0.2 on 2026-02-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_birth_date_alter_chatsession_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
