# Generated by Django 6.0.2 on 2026-03-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantanalysis',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='analyses/annotated/'),
        ),
    ]
