# Generated by Django 6.0.2 on 2026-03-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_plantanalysis_annotated_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='yolo_conf',
            field=models.FloatField(default=0.25, verbose_name='Уверенность (Confidence)'),
        ),
        migrations.AddField(
            model_name='user',
            name='yolo_imgsz',
            field=models.IntegerField(default=640, verbose_name='Размер фото для ИИ'),
        ),
        migrations.AddField(
            model_name='user',
            name='yolo_iou',
            field=models.FloatField(default=0.7, verbose_name='Порог перекрытия (IoU)'),
        ),
    ]
