# Generated by Django 6.0.2 on 2026-03-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chatmessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_annotated/'),
        ),
    ]
