# Generated by Django 6.0.2 on 2026-03-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chatmessage_annotated_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_tg_session_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
