# Generated by Django 6.0.2 on 2026-03-02 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_active_tg_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='annotated_image',
        ),
        migrations.CreateModel(
            name='MessageAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chat_annotated_history/')),
                ('conf', models.FloatField(verbose_name='Уверенность (Confidence)')),
                ('iou', models.FloatField(verbose_name='Порог перекрытия (IoU)')),
                ('imgsz', models.IntegerField(verbose_name='Размер фото для ИИ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='api.chatmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
