# Generated by Django 6.0.2 on 2026-03-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_chatmessage_annotated_image_messageannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageannotation',
            name='color_leaf',
            field=models.CharField(default='#16A34A', max_length=7),
        ),
        migrations.AddField(
            model_name='messageannotation',
            name='color_root',
            field=models.CharField(default='#9333EA', max_length=7),
        ),
        migrations.AddField(
            model_name='messageannotation',
            name='color_stem',
            field=models.CharField(default='#2563EB', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='color_leaf',
            field=models.CharField(default='#16A34A', max_length=7, verbose_name='Цвет листьев'),
        ),
        migrations.AddField(
            model_name='user',
            name='color_root',
            field=models.CharField(default='#9333EA', max_length=7, verbose_name='Цвет корней'),
        ),
        migrations.AddField(
            model_name='user',
            name='color_stem',
            field=models.CharField(default='#2563EB', max_length=7, verbose_name='Цвет стеблей'),
        ),
        migrations.AlterField(
            model_name='user',
            name='yolo_imgsz',
            field=models.IntegerField(default=1024, verbose_name='Размер фото для ИИ'),
        ),
    ]
