# Generated by Django 6.0.2 on 2026-03-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_messageannotation_color_leaf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageannotation',
            name='segments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
