# Generated by Django 6.0.2 on 2026-03-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_messageannotation_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageannotation',
            name='leaves',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='messageannotation',
            name='stems',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
