# Generated by Django 6.0.2 on 2026-03-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_messageannotation_leaves_messageannotation_stems'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calib_camera_matrix',
            field=models.JSONField(blank=True, null=True, verbose_name='Camera Matrix'),
        ),
        migrations.AddField(
            model_name='user',
            name='calib_cm2_per_pixel',
            field=models.FloatField(blank=True, null=True, verbose_name='см²/пиксель'),
        ),
        migrations.AddField(
            model_name='user',
            name='calib_dist_coeffs',
            field=models.JSONField(blank=True, null=True, verbose_name='Distortion Coefficients'),
        ),
        migrations.AddField(
            model_name='user',
            name='calib_mm_per_pixel',
            field=models.FloatField(blank=True, null=True, verbose_name='мм/пиксель'),
        ),
        migrations.AddField(
            model_name='user',
            name='calib_reprojection_error',
            field=models.FloatField(blank=True, null=True, verbose_name='Ошибка репроекции'),
        ),
    ]
