# Generated by Django 6.0.2 on 2026-03-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_calib_camera_matrix_user_calib_cm2_per_pixel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageannotation',
            name='leaf_area_cm2',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='messageannotation',
            name='stem_length_mm',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
