# Generated by Django 6.0.2 on 2026-03-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_messageannotation_leaf_area_cm2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageannotation',
            name='is_deep_scan',
            field=models.BooleanField(default=False),
        ),
    ]
