# Generated by Django 6.0.2 on 2026-03-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_messageannotation_is_deep_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageannotation',
            name='is_baked',
            field=models.BooleanField(default=False),
        ),
    ]
