# Generated by Django 6.0.2 on 2026-03-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageannotation',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Модель YOLO'),
        ),
    ]
