# Generated by Django 6.0.2 on 2026-03-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_model_name_to_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageannotation',
            name='metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
